"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = [
    ('res', ['res/iconmonstr-x-mark-4-240.png', 'res/iconmonstr-check-mark-6-240.png'])
]
OPTIONS = {
    'packages': ['PIL'],
    'iconfile': 'res/whittler_icon.icns',
}

setup(
    app=APP,
    name="Photo Whittler",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
